import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../../prisma.service';
import { GoogleGenerativeAI } from '@google/generative-ai';

@Injectable()
export class AiAnalysisService {
    private readonly logger = new Logger(AiAnalysisService.name);
    private genAI: GoogleGenerativeAI;
    private model: any;

    constructor(private prisma: PrismaService) {
        const apiKey = process.env.GEMINI_API_KEY;
        if (apiKey) {
            this.genAI = new GoogleGenerativeAI(apiKey);
            this.model = this.genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
        }
    }

    private getDBContext() {
        return `
      Database Schema:
      
      - Table "User": Represents agents, auditors, and managers.
        - id (uuid), name (string), email (string), role (AGENT, QA, QA_TL, ADMIN), eid (employee id)
      
      - Table "Campaign": Represents project groups.
        - id (uuid), name (string), isActive (boolean)
      
      - Table "Audit": Main evaluation data.
        - id (uuid), campaignId (uuid), score (float), status (DRAFT, IN_PROGRESS, SUBMITTED, RELEASED, DISPUTED, REAPPEALED)
        - agentId (uuid) references User.id
        - auditorId (uuid) references User.id
        - submittedAt (datetime), ticketReference (string)
      
      - Table "Dispute": Analysis of contested audits.
        - id (uuid), auditId (uuid), status (PENDING_QA_REVIEW, QA_REJECTED, REAPPEALED, FINALIZED)
        - raisedById (uuid) references User.id
      
      - Table "MonitoringForm": Logic for the audits.
        - id (uuid), name (string), campaignId (uuid)

      Relationships:
      - Audit.agentId -> User.id
      - Audit.campaignId -> Campaign.id
      - Dispute.auditId -> Audit.id
    `;
    }

    async analyze(prompt: string, filters?: any) {
        if (!this.model) {
            throw new Error('Gemini API Key not configured');
        }

        // 1. Generate SQL
        const sqlPrompt = `
      You are an expert PostgreSQL developer. 
      Given the following schema:
      ${this.getDBContext()}
      
      Translate this natural language request into a valid PostgreSQL SELECT query:
      "${prompt}"
      
      ${filters ? `Apply these filters as well: ${JSON.stringify(filters)}` : ''}
      
      Rules:
      - Return ONLY the raw SQL query.
      - No markdown, no backticks, no explanations.
      - Use triple quotes for strings if needed.
      - Ensure the query is read-only (SELECT only).
      - If you need to join User for names, do it.
    `;

        const result = await this.model.generateContent(sqlPrompt);
        const sql = result.response.text().trim().replace(/```sql|```/g, '');

        this.logger.log(`Generated SQL: ${sql}`);

        // 2. Security Check (Basic)
        const forbidden = ['DROP', 'DELETE', 'UPDATE', 'INSERT', 'ALTER', 'TRUNCATE'];
        if (forbidden.some(word => sql.toUpperCase().includes(word))) {
            throw new Error('Unauthorized query generated by AI');
        }

        try {
            // 3. Execute SQL
            const data: any[] = await this.prisma.$queryRawUnsafe(sql);

            // 4. Generate Insights
            const insightPrompt = `
        You are a Data Analyst for a Quality Management System.
        The user asked: "${prompt}"
        The database returned this raw JSON data:
        ${JSON.stringify(data.slice(0, 10))} ${data.length > 10 ? `... (showing 10 of ${data.length} rows)` : ''}
        
        Provide a concise, professional analysis of this data. 
        Identify trends, top performers, or areas of concern.
        Use bullet points for clarity.
        If no data was found, explain why.
      `;

            const insightResult = await this.model.generateContent(insightPrompt);
            const insight = insightResult.response.text().trim();

            return {
                insight,
                sql,
                data,
                count: data.length
            };
        } catch (error) {
            this.logger.error(`Error executing AI SQL: ${error.message}`);
            throw new Error('Failed to analyze database data. Please try rephrasing your request.');
        }
    }
}
